language: c
compiler:
    - gcc

dist: trusty
sudo: required

addons:
    apt:
        sources:
            -ubuntu-toolchain-r-test
        packages:
            - gcc-6

env:
    global:
        - LD_LIBRARY_PATH="/usr/local/lib"
        - C_INCLUDE_PATH=".:/usr/include/mysql/:/usr/include"
        - MYSQL_HOST="localhost"
        - MYSQL_USER="root"
        - MYSQL_PASS=
        - REDIS_HOST="localhost"
        - REDIS_PORT="6379"

services:
    - redis-server
    - mysql

install: 
    - sudo apt-get install libmysqlclient-dev 
    - sudo apt-get install libevent-dev
    - scripts/setup_redis.sh 

before_script:
    - cd scripts && ./setup_db.sh root
    - gcc --version

script:
    - make && make test
